### ISSUE TITLE
ur3 pykdl

### ISSUE THREAD

**Issue by Mr-Xia-6** [cambel/ur3#5]
inverse_kinematics cannot get a solution.

**Comment by cambel** [comment]
Hi, thanks for using my repository. 

Can you please elaborate more on what the problem is? What are you trying and what error are you getting?

Also, if is an IK problem, it is common to have missing IK solutions depending on many things, like hitting the robot's workspace limits or getting close to singularity joint configurations. Also, I use the IKFAST lib which cannot find 100% solutions.
